/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sl1_pro;

/**
 *
 * @author lenovo
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.text.*;
import java.sql.Date; 
import javax.swing.JFrame;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;

public class blood_details extends javax.swing.JFrame {

    /**
     * Creates new form blood_details
     */
    public blood_details() {
        initComponents();
    }
    public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(871, 498));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(871, 498));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Blood Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 100, 160, 50);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donated by");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 170, 79, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 260, 79, 26);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Donation date");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 310, 79, 20);
        getContentPane().add(jXDatePicker1);
        jXDatePicker1.setBounds(380, 310, 230, 24);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood Type");
        jLabel5.setAlignmentY(0.0F);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 220, 79, 20);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 170, 292, 22);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton1.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton1, MaterialColors.BLACK);
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 380, 376, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jComboBox1.setAlignmentY(0.0F);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(380, 220, 62, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(380, 260, 160, 22);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("units");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 260, 50, 20);

        jPanel1.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Close Window_25px.png"))); // NOI18N
        jLabel8.setToolTipText("Close");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setIconTextGap(0);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Minimize Window_25px.png"))); // NOI18N
        jLabel9.setToolTipText("Minimize");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Home_45px.png"))); // NOI18N
        jLabel10.setToolTipText("Home");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 739, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/blue_abstract.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 870, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static java.sql.Date convertJavaDateToSqlDate(java.util.Date date)
	{
		// java.util.Date contains both date and time information
		// java.sql.Date contains only date information (without time)
		return new java.sql.Date(date.getTime());
	}
    
    
    public static Date addDays(Date d, int days)
    {
        d.setTime(d.getTime() + days * 1000 * 60 * 60 * 24);
        return d;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(validate_required() && validate_bloodtype()){
        try{
        Class.forName("com.mysql.jdbc.Driver");
        int cost;
        int quan = Integer.parseInt(jTextField2.getText());
        
        
       
        java.sql.Date sqlDate = convertJavaDateToSqlDate(jXDatePicker1.getDate());
        DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String szDate = oDateFormat.format(sqlDate);
        Date expDate = addDays(sqlDate, 20);
       
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")) {
                String Query = "INSERT INTO blood(blood_group, quantity, from_date, expiry_date) VALUES('"+combo_box_type+"','"+jTextField2.getText()+"','"+szDate+"','"+expDate+"')";
                PreparedStatement st = con.prepareStatement(Query);
                st.execute();
            }
            String entered_bloodtype = jTextField1.getText();
            int entered_quantity = Integer.parseInt(jTextField2.getText());
            b_grp = (String) jComboBox1.getSelectedItem();
            try{
                Class.forName("com.mysql.jdbc.Driver");
                try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")) {
                String Query = "SELECT stock FROM blood_stock WHERE type ='"+b_grp+"'";
                PreparedStatement st = con.prepareStatement(Query);
                ResultSet results = st.executeQuery(Query);
                results.next();
                int flag=0;
            
                if(flag==0)
                {
                    int new_stock = results.getInt("stock") + entered_quantity;
                    System.out.println(new_stock);
                    String update_stock = "UPDATE blood_stock SET stock ='"+new_stock+"' WHERE type ='"+b_grp+"'";
                    PreparedStatement st2 = con.prepareStatement(update_stock);
                    st2.execute();
                     
                    flag=1;
                }
                JOptionPane.showMessageDialog(null,"Blood details updated successfully");
                main_dashboard var1 = new main_dashboard();
                var1.setVisible(true);
    }} catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        } }
    catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         combo_box_type = (String) jComboBox1.getSelectedItem();         // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:

        main_dashboard var = new main_dashboard();
        var.setVisible(true);
        close();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(blood_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(blood_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(blood_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(blood_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new blood_details().setVisible(true);
            }
        });
    }
    
    public boolean validate_required(){
        if(jTextField1.getText().equals("") || jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill all fields");
            return false;
        }
        return true;
    }
     public boolean validate_bloodtype(){
        if(jComboBox1.getSelectedItem().equals("Select")){
        JOptionPane.showMessageDialog(null, "Please enter valid blood type");
       
        return false;
    }
    return true;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    // End of variables declaration//GEN-END:variables
    private String combo_box_type;
    private String b_grp;
}
