/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sl1_pro;

/**
 *
 * @author lenovo
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;
public class hospital_login extends javax.swing.JFrame {

    /**
     * Creates new form hospital_login
     */
    public hospital_login() {
        initComponents();
    }
public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(730, 478));
        setPreferredSize(new java.awt.Dimension(730, 478));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospital Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 130, 162, 29);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(128, 190, 80, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(125, 250, 80, 16);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton1.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton1, MaterialColors.BLACK);
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 310, 170, 25);

        jButton2.setText("Reset");
        jButton2.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton2.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton2, MaterialColors.BLACK);
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 310, 160, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 190, 277, 22);

        jButton3.setText("Sign Up");
        jButton3.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton3.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton3, MaterialColors.BLACK);
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 310, 130, 25);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Home_45px.png"))); // NOI18N
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton4.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton4, MaterialColors.BLACK);
        getContentPane().add(jButton4);
        jButton4.setBounds(20, 20, 100, 70);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(230, 250, 280, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/blue_abstract.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 730, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
          main_dashboard var1 = new main_dashboard();
          var1.setVisible(true); 
    }   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String entered_username = jTextField1.getText();
        String entered_password = new String(jPasswordField1.getPassword());
        try{
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")) {
            String Query = "SELECT username, password FROM hospital_details";
            PreparedStatement st = con.prepareStatement(Query);
            ResultSet results = st.executeQuery(Query);
            while(results.next())
            {
                String uname = results.getString("username");
                String pass = results.getString("password");
                
                if(entered_username.equals(uname) && entered_password.equals(pass))
                {
                    hospital_dashboard var = new hospital_dashboard();
                    var.setVisible(true);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Invalid credentials");
                    jTextField1.setText("");
                    jTextField1.setText("");
                }
            }
            
    }//GEN-LAST:event_jButton1ActionPerformed

//GEN-FIRST:event_jButton4ActionPerformed
 
//GEN-LAST:event_jButton4ActionPerformed
/*       */ }
     catch(ClassNotFoundException | SQLException e)
        {
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hospital_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hospital_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hospital_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hospital_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hospital_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
