/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sl1_pro;

/**
 *
 * @author suraj
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import mdlaf.*;
import mdlaf.animation.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import static javafx.beans.binding.Bindings.concat;
import javax.swing.JFrame;
import mdlaf.utils.MaterialColors;
public class Manager_dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public Manager_dashboard() {
        initComponents();
        fetch();
     
    }
       public void close(){
 
 WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
 
 }
    
    public void fetch(){
        try{ Class.forName("com.mysql.jdbc.Driver");
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")){
           // String create_view = "CREATE OR REPLACE VIEW display_details AS select *from persons inner join donor on persons.ID=donor.ID";
            //PreparedStatement st2 = con.prepareStatement(create_view);
            //st2.execute();
           String query = "select *from persons inner join donor on persons.ID=donor.ID";
            PreparedStatement st = con.prepareStatement(query);
            ResultSet result = st.executeQuery(query);
            jTable3.setModel(DbUtils.resultSetToTableModel(result));
        } 
        }catch(Exception e){
             System.out.println(e);
            
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(954, 503));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(954, 503));
        getContentPane().setLayout(null);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Donor Details");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 110, 76, 16);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(61, 140, 840, 180);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(590, 100, 94, 22);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton1.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton1, MaterialColors.BLACK);
        getContentPane().add(jButton1);
        jButton1.setBounds(699, 100, 140, 25);

        jButton2.setText("Delete Record");
        jButton2.setMaximumSize(new java.awt.Dimension(200, 40));
        jButton2.setMinimumSize(new java.awt.Dimension(200, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton2.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton2, MaterialColors.BLACK);
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 340, 250, 40);

        jButton3.setText("Update Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBackground (MaterialColors.LIGHT_BLUE_400);
        jButton3.setForeground (Color.WHITE);
        MaterialUIMovement.add (jButton3, MaterialColors.BLACK);
        getContentPane().add(jButton3);
        jButton3.setBounds(580, 340, 260, 40);

        jPanel1.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Close Window_25px.png"))); // NOI18N
        jLabel5.setToolTipText("Close");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setIconTextGap(0);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Minimize Window_25px.png"))); // NOI18N
        jLabel6.setToolTipText("Minimize");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/Home_45px.png"))); // NOI18N
        jLabel7.setToolTipText("Home");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("W E L C O M E");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(323, 323, 323)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sl1_pro/images/blue_abstract.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 950, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search_ID = jTextField1.getText();
        System.out.println(search_ID);
          try{Class.forName("com.mysql.jdbc.Driver");
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")){
            
            String q = "select *from persons where ID='"+search_ID+"'";
            String q2 ="select *from donor where ID='"+search_ID+"'";
             PreparedStatement st = con.prepareStatement(q);
            ResultSet result1 = st.executeQuery(q);
           // PreparedStatement st1 = con.prepareStatement(q);
           // ResultSet result2 = st1.executeQuery(q2);
           // ResultSet result =result1 + result2;
            
             jTable3.setModel(DbUtils.resultSetToTableModel(result1));
            
            
        }
        }catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{Class.forName("com.mysql.jdbc.Driver");
        try(Connection con = DriverManager.getConnection("jdbc:mysql://localhost/SL1_pro?" + "user=root&password=")){
                int row = jTable3.getSelectedRow();
            
            int column = 9;          
               
            String value = jTable3.getModel().getValueAt(row, column).toString();
              String id ="select ID from donor where aadhar_no='"+value+"'";
              System.out.println(value);
              PreparedStatement st = con.prepareStatement(id);
             
            ResultSet result = st.executeQuery(id);
            result.next();
            System.out.println(result.getString("ID"));
            String delete = "delete from donor where aadhar_no='"+value+"' ";
           String delete_per="delete from persons where ID='"+result.getString("ID")+"'";
           
             System.out.println(value);
            PreparedStatement st1 = con.prepareStatement(delete);
             
            st1.execute();
            PreparedStatement st2 = con.prepareStatement(delete_per);
             
            st2.execute();
           
            DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
            model.removeRow( row );
            JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
        }
         }catch(Exception e){
             System.out.println(e);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable3.getSelectedRow();
            
            int column = jTable3.getSelectedColumn();          
               
            String value = jTable3.getModel().getValueAt(row, 9).toString();
            System.out.println(value);
            SL1_pro.value=value;
             
        // JOptionPane.showMessageDialog(null,"");
        update var = new update();
            var.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked

        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:

        main_dashboard var = new main_dashboard();
        var.setVisible(true);
        close();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_dashboard().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
